### PR TITLE
Fix minio bucket name invalid path

### PR DESCRIPTION
**Pull request by andre-vspry**
When using a bucket for storage and setting relevenat MINIO_ environment variables, serve-api fails to start.

See #295

### CODE REVIEW

**Comment by andre-vspry** [comment]
@vicpatel any progress on this?

**Comment by andre-vspry** [comment]
Fixes #295

**Comment by vicpatel** [comment]
Hey @andre-vspry,
I have pushed some changes regarding minio, and also added some tests.
here is branch `2021.9.x-fix-minio-bucket-separator`, If you don't mind can we change the base branch to this,
Please feel free to add feedback or Improve the tests as you like.

**Comment by andre-vspry** [comment]
Please keep this open for now. I'd like another review.

**Pull request closed without merging**
